### ISSUE TITLE
Backend is showing up in services

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#128] opened 2020-11-24 15:51 UTC
## Use Case
I deployed Hypertrace with latest charts on EKS and I am using hotrod to application to generate traces. I am observing that redis (which is backend) is showing up in services. Which wasn't happening earlier. 

refer screenshots below:
<img width="1680" alt="Screenshot 2020-11-24 at 9 19 37 PM" src="https://user-images.githubusercontent.com/26570044/100117421-c6cb8500-2e9a-11eb-9388-dfb1f56f5b83.png">

<img width="1680" alt="Screenshot 2020-11-24 at 9 20 32 PM" src="https://user-images.githubusercontent.com/26570044/100117527-e5ca1700-2e9a-11eb-95dc-c97f069a0106.png">

Initially, I used charts from https://github.com/hypertrace/hypertrace and then I updated charts here: https://github.com/hypertrace/hypertrace/pull/127 and used those for deployment and still issue persists so not related to chart versions, I assume. 

## Proposal
We should find what's causing it and address this as soon as possible. 

cc: @buchi-busireddy @jake-bassett @kotharironak

**Comment by rish691** [comment] 2020-11-24 16:10
Because some of the pr for supporting otel semantics has been merged.

**Comment by JBAhire** [comment] 2020-11-25 05:01
But, earlier charts were from last week and there was same issue.

**Comment by buchi-busireddy** [comment] 2020-11-25 06:12
> I am guessing it is because some of the changes for supporting otel semantics has been merged.
> @JBAhire how are you instrumenting hotrod?

@rish691 are you saying it could be a bug? To me it sounds like a clear bug.

**Comment by rish691** [comment] 2020-11-25 07:26
I was under the assumption that the code with otel semantics changes has been used for this. Which is not the case.
Regardless of that it is a bug.

**Comment by rish691** [comment] 2020-11-29 07:50
So, I tried out locally running hotrod with latest hypertrace-ingester image (release tag 0.3.3). Seems to be working fine. 

<img width="1598" alt="Screenshot 2020-11-29 at 3 22 55 AM" src="https://user-images.githubusercontent.com/6513075/100536277-8cb90500-3245-11eb-9c2e-a7478b8f2f14.png">
<img width="1913" alt="Screenshot 2020-11-29 at 3 22 23 AM" src="https://user-images.githubusercontent.com/6513075/100536281-917db900-3245-11eb-9710-c7bc3e6a3e44.png">

**Comment by JBAhire** [comment] 2020-12-04 06:00
@rish691 , still able to produce it when deployed with latest charts pushed here: https://github.com/hypertrace/hypertrace/pull/127

<img width="2560" alt="Screenshot 2020-12-04 at 11 16 51 AM" src="https://user-images.githubusercontent.com/26570044/101127665-083efb80-3624-11eb-9574-60469dd6a3e7.png">

**Comment by rish691** [comment] 2020-12-04 06:22
@JBAhire this is strange. If you get some time can you also try locally with docker-compose. 
I will also check it.

**Comment by kotharironak** [comment] 2020-12-21 14:56
This was not reproducible locally. It was reproducible on EKS as mentioned in the description. Our observation was that it was happening as the collector was dropping spans.
```
{"level":"warn","ts":1608035584.3451312,"caller":"queued/queued_processor.go:190","msg":"Span batch dropped","processor":"jaeger-sender-test","#spans":1,"spanSource":"jaeger"}
{"level":"warn","ts":1608035584.3456793,"caller":"queued/queued_processor.go:190","msg":"Span batch dropped","processor":"jaeger-sender-test","#spans":1,"spanSource":"jaeger"}
{"level":"warn","ts":1608035584.3473406,"caller":"queued/queued_processor.go:190","msg":"Span batch dropped","processor":"jaeger-sender-test","#spans":1,"spanSource":"jaeger"}
```

**Comment by buchi-busireddy** [comment] 2020-12-21 17:30
@JBAhire @kotharironak I suspect this could have been due to the span.kind related issues, which I think we have fixed now. cc @rish691 
Dropping of spans could wrongly treat services as backends, but not vice versa.

**Comment by kotharironak** [comment] 2020-12-24 11:15
The issue is happening as spans are getting dropped for a given trace. The spans get dropped due to multiple reasons. But, in this case, it is dropped at the local collector level if you generate too much load.

Below are the example scenarios:
Case (1)  http://a3d8cd97882df4407a541d9dc7d30c2c-494597604.us-west-2.elb.amazonaws.com:2020/trace/00000000000000003492689acfbd8344;spanId=649826ad7e4a18c1?time=1608730432802-1608731332802

Case (2) http://a3d8cd97882df4407a541d9dc7d30c2c-494597604.us-west-2.elb.amazonaws.com:2020/trace/000000000000000012cffc6a979e4cea;spanId=4af6aa6a3d5232f7?time=1608730199600-1608731999600
 

The below is corresponding Jeager traces
1. full trace 
[trace-34926.json.txt](https://github.com/hypertrace/hypertrace/files/5739378/trace-34926.json.txt)

2. trace with a dropped span 
[trace-34926-dropped.json.txt](https://github.com/hypertrace/hypertrace/files/5739380/trace-34926-dropped.json.txt)

Using the trace with the dropped span, I was able to repo locally with docker-compose setup
<img width="1679" alt="Screenshot 2020-12-24 at 4 05 05 PM" src="https://user-images.githubusercontent.com/53209990/103085338-6c435700-4607-11eb-8b16-3751b7f4164d.png">

I had configured my local collector to send spans both to EKS and my local Jager endpoints. After finding, a trace with dropped spans for a trace, I had to manually construct the trace from a fully collected trace at locally. we have an issue logged for this for downloading the HT trace in re-ingestable format.

**Comment by kotharironak** [comment] 2020-12-24 11:29
\

> @JBAhire @kotharironak I suspect this could have been due to the span.kind related issues, which I think we have fixed now. cc @rish691
> Dropping of spans could wrongly treat services as backends, but not vice versa.

@rish691 @buchi-busireddy As mentioned above, I was able to repro with `main` branch's docker-compose file, and it uses the latest image for `hypertrace-ingester` (which was 7 day ago) and `main` branch image for `hypertrace-service`. I will retry locally building `hypertrace-ingester`

**Comment by buchi-busireddy** [comment] 2020-12-28 21:08
@kotharironak I don't think I understand the root cause though. Why would losing some spans cause a backend to come up as a service?

**Comment by kotharironak** [comment] 2020-12-30 06:54
@buchi-busireddy @JBAhire @rish691 

This is the case where a span is a single node.
a. its leaf sapn
b. its an exit span
c. it has no parents

In our current implementation, we do take care of the case leaf span having a parent. The above is an edge scenario, but it can possible as visible in the captured scenario `trace-34926-dropped.json` 

Trace:  trace-34926-dropped.json
Trace graph:
<img width="1666" alt="Screenshot 2020-12-29 at 2 47 03 PM" src="https://user-images.githubusercontent.com/53209990/103334891-223ff280-4a99-11eb-9df3-25d994df5a02.png">

Redis span:
```
{
               "traceID":"3492689acfbd8344",
               "spanID":"649826ad7e4a18c1",
               "operationName":"FindDriverIDs",
               "references":[
                  {
                     "refType":"CHILD_OF",
                     "traceID":"3492689acfbd8344",
                     "spanID":"7f4bddb2b22af7bc"
                  }
               ],
               "startTime":1608731091292052,
               "duration":24793,
               "tags":[
                  {
                     "key":"span.kind",
                     "type":"string",
                     "value":"client"
                  },
                  {
                     "key":"param.location",
                     "type":"string",
                     "value":"577,322"
                  },
                  {
                     "key":"internal.span.format",
                     "type":"string",
                     "value":"jaeger"
                  }
               ],
               "logs":[
                  {
                     "timestamp":1608731091316768,
                     "fields":[
                        {
                           "key":"event",
                           "type":"string",
                           "value":"Found drivers"
                        },
                        {
                           "key":"level",
                           "type":"string",
                           "value":"info"
                        }
                     ]
                  }
               ],
               "processID":"p4",
               "warnings":null
            }
 ```

So, in the above case, we create `redis` as a separate service b'cose the code will not qualify for backend conditions.
a. DefaultServiceEntityEnricher will not able to find parent service (https://github.com/hypertrace/hypertrace-trace-enricher/blob/435d21caab170c5b8d207785204b61839089a599/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/DefaultServiceEntityEnricher.java#L75)
b. ClientSpanEndpointResolver will not able to create facede backend entity(https://github.com/hypertrace/hypertrace-trace-enricher/blob/435d21caab170c5b8d207785204b61839089a599/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/resolver/backend/ClientSpanEndpointResolver.java)

There is two way to handle this case:
a. Add the case for a single node in DefaultServiceEntityEnricher and  ClientSpanEndpointResolver for specifically checking for known backends based on service names - servicename in [`redis`, `mongo` ....]
b. Add the case for a single node in DefaultServiceEntityEnricher and corresponding backend resolver (JDBC, Redis, Mongo) for known backend based on service names - servicename in [`redis`, `mongo` ....]

I would prefer the option (b) as option (a) still have possibilities of creating two backend for same trace. As in options (a), we are setting protocol as `UNKNOWN` and it is used as identifying attributes.

Let me know your thoughts for options.

**Comment by kotharironak** [comment] 2020-12-30 07:50
@buchi-busireddy @rish691 @JBAhire BTW, I have raised PR (https://github.com/hypertrace/hypertrace-ingester/pull/93) for correcting dependencuy order for backend entity enricher.

**Comment by jcchavezs** [comment] 2020-12-30 14:01
I think both a and b proposals for solution are problematic. I don't seem to understand the reason why the spans are get dropped as you said load isn't the problem.

**Comment by rish691** [comment] 2021-02-11 07:42
> I think both a and b proposals for solution are problematic. 

I second that. Having a hardcoded check on names might be problematic and seems like a short term solution. 

Our definition of backend is an entity which is un-instrumented, based on this definition there are various checks in our
code to identify such entity (based on parent child in the Trace), currently we cannot identify service/backend based only on a single span, there is some context information required. The proposal seems to be overriding this approach. 

If we do want to classify backends based on different criteria like database type etc., it needs more careful revision of our
definition of backend.  

That's just my 2 cents.

**Comment by kotharironak** [comment] 2021-02-24 13:47
Based on the investigation, this is happening due to instrumentation. 

Consider the trace ("traceID":"3492689acfbd8344") described in file - `trace-34926.json.txt`.

Now consider span ("spanId" : "772dc9ba8866353d")
```
"spanId" : "772dc9ba8866353d"
"processID":"p3" referes to "serviceName":"frontend"
"peer.service" is "driver"
```
Now consider span  ("spanID":"1bee53b7a5a0f8f2")
```
"spanID":"1bee53b7a5a0f8f2",
"processID":"p2" which is "serviceName":"mysql"
"peer.service" is  "mysql"
```
As per my understanding `process ID` will refer to a process that has generated span. However, it seems that in some places it is referring to source and in some places, it is referring to destination service. 

So, either hotrod is not instrumented properly or jaeger sdk's is generating overloaded information for processID. The other existing tools are listing the group of services mentioned in traces and forming trace graphs using parent-child relations of spans. In HT, it identifies entities and their relationships among them by using span data, a trace graph,  and identifying service edge boundaries using span.kind information.

@jcchavezs Can you have context on what should be the value of processID?

**Comment by kotharironak** [comment] 2021-03-22 09:43
Closing this issue as the corner case is handled.

**Closed by kotharironak** 2021-03-22 09:43 UTC
Labels: bug
